site_name: mlr tutorial
site_dir: devel/html
docs_dir: svg/docs
repo_url: https://github.com/mlr-org/mlr/
use_directory_urls: False
theme: 'mkdocs'
theme_dir: custom_theme
extra_css: ['css/custom_mlr.css', 'css/custom_highlight.css']
markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML']
pages:
- Home: 'index.md'
- Basics:
    - 'Tasks': 'task.md'
    - 'Learners': 'learner.md'
    - 'Train': 'train.md'
    - 'Predict': 'predict.md'
    - 'Performance': 'performance.md'
    - 'Resampling': 'resample.md'
    - 'Tuning': 'tune.md'
    - 'Benchmark Experiments': 'benchmark_experiments.md'
    - 'Parallelization': 'parallelization.md'
    - 'Visualization': 'visualization.md'
- Advanced:
    - 'Configuration': 'configureMlr.md'
    - 'Wrapped Learners': 'wrapper.md'
    - 'Preprocessing': 'preproc.md'
    - 'Imputation': 'impute.md'
    - 'Bagging': 'bagging.md'
    - 'Advanced Tuning': 'advanced_tune.md'
    - 'Feature Selection': 'feature_selection.md'
    - 'Nested Resampling': 'nested_resampling.md'
    - 'Cost-Sensitive Classification': 'cost_sensitive_classif.md'
    - 'Imbalanced Classification Problems': 'over_and_undersampling.md'
    - 'ROC Analysis': 'roc_analysis.md'
    - 'Multilabel Classification': 'multilabel.md'
    - 'Learning Curves': 'learning_curve.md'
    - 'Partial Dependence Plots': 'partial_dependence.md'
    - 'Classifier Calibration Plots': 'classifier_calibration.md'
    - 'Hyperparameter Tuning Effects': 'hyperpar_tuning_effects.md'
    - 'Out-of-Bag Predictions': 'out_of_bag_predictions.md'
- Extend:
    - 'Create Custom Learners': 'create_learner.md'
    - 'Create Custom Measures': 'create_measure.md'
    - 'Create Imputation Methods': 'create_imputation.md'
    - 'Create Custom Filters': 'create_filter.md'
- Appendix:
    - 'Example Tasks': 'example_tasks.md'
    - 'Integrated Learners': 'integrated_learners.md'
    - 'Implemented Performance Measures': 'measures.md'
    - 'Integrated Filter Methods': 'filter_methods.md'
