site_name: mlr tutorial
site_dir: devel/html
repo_url: https://github.com/mlr-org/mlr/
use_directory_urls: False
theme: 'mkdocs'
theme_dir: custom_theme
extra_css: ['css/custom_mlr.css', 'css/custom_highlight.css']
markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML']
pages:
- Home: 'index.md'
- Basics:
    - 'Tasks': 'task.md'
    - 'Learners': 'learner.md'
    - 'Train': 'train.md'
    - 'Predict': 'predict.md'
    - 'Performance': 'performance.md'
    - 'Resampling': 'resample.md'
    - 'Benchmark Experiments': 'benchmark_experiments.md'
    - 'Parallelization': 'parallelization.md'
    - 'Visualization': 'visualization.md'
- Advanced:
    - 'Configuration': 'configureMlr.md'
    - 'Wrapped Learners': 'wrapper.md'
    - 'Preprocessing': 'preproc.md'
    - 'Imputations': 'impute.md'
    - 'Bagging': 'bagging.md'
    - 'Tuning': 'tune.md'
    - 'Feature Selection': 'feature_selection.md'
    - 'Cost-Sensitive Classification': 'cost_sensitive_classif.md'
    - 'Imbalanced Classification Problems': 'over_and_undersampling.md'
    - 'ROC Analysis': 'roc_analysis.md'
    - 'Multilabel Classification': 'multilabel.md'
    - 'Learning Curve': 'learning_curve.md'
    - 'Partial Prediction Plots': 'partial_prediction.md'
- Extend:
    - 'Create Custom Learners': 'create_learner.md'
    - 'Create Custom Measures': 'create_measure.md'
    - 'Create an Imputation Method': 'create_imputation.md'
- Appendix:
    - 'Example Tasks': 'example_tasks.md'
    - 'Integrated Learners': 'integrated_learners.md'
    - 'Implemented Performance Measures': 'measures.md'
    - 'Integrated Filter Methods': 'filter_methods.md'
